version: '3.8'

services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=local_test
      - POSTGRES_PASSWORD=local_test
      - POSTGRES_DB=local_test
    volumes:
      - .:/app
    depends_on:
      - db

  app_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=local_test
      - POSTGRES_PASSWORD=local_test
      - POSTGRES_DB=local_test
