version: '3.8'

services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=local_test
      - POSTGRES_PASSWORD=local_test
      - POSTGRES_DB=local_test
      - BROKER_URL=broker
      - BROKER_USER=guest
      - BROKER_PASSWORD=guest
    volumes:
      - .:/app
    depends_on:
      - db
      - broker

  app_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - broker

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=local_test
      - POSTGRES_PASSWORD=local_test
      - POSTGRES_DB=local_test
    ports:
      - "5432:5432"

  broker:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest